# Generated by Django 2.2.4 on 2019-08-26 03:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidoPaterno', models.CharField(max_length=35)),
                ('apellidoMaterno', models.CharField(max_length=35)),
                ('nombres', models.CharField(max_length=35)),
                ('documento', models.CharField(max_length=11)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('descripcion', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('Mu', 'Museos'), ('Re', 'Restaurantes'), ('Bic', 'Paseos de Bicileta'), ('SO', 'Sitios ocultos')], default='Mu', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('precio', models.CharField(max_length=11)),
                ('categoria', models.CharField(choices=[('Mu', 'Museos'), ('Re', 'Restaurantes'), ('Bic', 'Paseos de Bicileta'), ('SO', 'Sitios ocultos')], default='Mu', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=150)),
                ('nombres', models.CharField(max_length=30)),
                ('documento', models.CharField(max_length=11)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('usuario', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=254)),
                ('user', models.ForeignKey(null=True, on_delete='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
