# Generated by Django 2.2.4 on 2019-08-19 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdministracionGuia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuaio',
            new_name='Usuario',
        ),
    ]
