# Generated by Django 2.2.1 on 2019-09-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministracionGuia', '0002_auto_20190902_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
