# Generated by Django 2.2.1 on 2019-08-25 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdministracionGuia', '0002_auto_20190818_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guia',
            old_name='ApellidoMaterno',
            new_name='apellidoMaterno',
        ),
        migrations.RenameField(
            model_name='guia',
            old_name='ApellidoPaterno',
            new_name='apellidoPaterno',
        ),
        migrations.RenameField(
            model_name='guia',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='guia',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='guia',
            old_name='Documento',
            new_name='documento',
        ),
        migrations.RenameField(
            model_name='guia',
            old_name='FechaNacimiento',
            new_name='fechaNacimiento',
        ),
        migrations.RenameField(
            model_name='guia',
            old_name='Nombres',
            new_name='nombres',
        ),
        migrations.RenameField(
            model_name='guia',
            old_name='Sexo',
            new_name='sexo',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='Precio',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='FechaNacimiento',
            new_name='fechaNacimiento',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Sexo',
            new_name='sexo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ApellidoMaterno',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ApellidoPaterno',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Documento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Nombres',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='documento',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.ForeignKey(null=True, on_delete='', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
